### ISSUE TITLE
Create and add to new ECHO-Geo repo

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Sunrise#1]
ECHO-Geo repo will store GeoJSONs representing different MA geographies that we can load in to the ECHO-Sunrise notebook.

- congressional districts
- HUC 12 (?) watersheds
- counties
- zip codes
- municipalities
- State House districts
- etc.

**Comment by ericnost** [comment]
Created here: https://github.com/edgi-govdata-archiving/ECHO-Geo

**Comment by ericnost** [comment]
#4

**Comment by mraisle** [comment]
the ECHO_geo repo has counties, municipalities (yay, Steve!), and counties. @ericnost you mentioned you have all others in this list they just need to be uploaded. So we can close this issue?

**Comment by ericnost** [comment]
Added all others now. Closing.
