### ISSUE TITLE
Difficulty Dowloading Multiple Datasets 

### ISSUE THREAD

**Issue by mraisle** [edgi-govdata-archiving/ECHO-Sunrise#11]
When downloading data, even if I have closed the window and completely run the notebook again, the csvs that are available for me to download reflect the choices I selected the first time I ran the notebook.

**Comment by ericnost** [comment]
Thanks for posting this. Just to confirm - the data in the CSVs themselves was the same each time? Currently, the name of the file does not change no matter your selections (it should).

**Comment by mraisle** [comment]
I honestly did not even check the data itself, just saw the name. That's probably what it was!

**Comment by mraisle** [comment]
Can you add me to this repo so i can assign/unassign/label, etc?

**Comment by ericnost** [comment]
Fixed.
