### ISSUE TITLE
Add more description about who this was developed for and why?

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/ECHO-Sunrise#18]
should we add a line in the top of the notebook "This notebook was developed by EDGI for Sunrise Boston to assist them in analyzing data on green house gas emissions and other air pollutants in Massachusetts"

**Comment by mraisle** [comment]
yes! I think so! Eric and I have discussed a few times now adding context to the notebook via google doc write-up so everyone has a chance to contribute, then Eric or I could put it in. We're waiting until we get to a more final draft of the notebook itself to do this.

**Comment by mraisle** [comment]
Merging this with document in issue #24 and closing this issue
