### ISSUE TITLE
split project into exploratory and targeted notebooks

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Sunrise#19]
Exploratory notebook:
1. Essentially same structure as the notebook now but including to the greatest extent possible, more data sets so that Sunrise can see what's of interest to them for a potential new campaign. Basically, it would be a MA-specific version of Cross-Program, but with some more ranking and mapping features built in.
2. Remove prisons analysis, as this harms-based approach doesn't make sense for a lot of data sets and it's also ethically questionable.
3. Add some sort of environmental crime analysis. This is hard to do in an exploratory notebook where users can select from several different kinds of data sets, some of which are not readily interpreted as environmental crime (e.g. inspections)

Targeted notebook:
Outline here - https://docs.google.com/document/d/1XV2ZRbg9b4KvNwMMqjJ9yF21kHB0ilYRmXOEoKKub2E/edit?usp=sharing

Deadline: 
July 9

**Comment by Frijol** [comment]
Should we close?

**Comment by ericnost** [comment]
Closed
