### ISSUE TITLE
The last mapping cell does not work for CAA violations and penalties.

### ISSUE THREAD

**Issue by maalvikabhat** [edgi-govdata-archiving/ECHO-Sunrise#26]

**Comment by ericnost** [comment]
Steve, would you be willing to help look into this? Here is the error:

![image](https://user-images.githubusercontent.com/6888951/87468888-6113e600-c5e8-11ea-8d0d-78111d29c6e9.png)

This appears to happen when there are few facilities or violations/penalties. The quantile function produces 'nan' for some reason.

**Comment by shansen5** [comment]
It can't compute quantiles on small sets.  Added test for small sets and for NaN quantiles, and use default radius for marker.  In sh_issues branch.

**Comment by ericnost** [comment]
Awesome, thanks!
