### ISSUE TITLE
Would be cool to add a comment explaining this a little more, specifically where it's being cloned to

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Sunrise#40]
Would be cool to add a comment explaining this a little more, specifically where it's being cloned to

_Originally posted by @Frijol in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ4MzIyMzc5/pull_request_reviews/more_threads_

**Comment by shansen5** [comment]
Added some brief description for colab in the cell before the cloning.  In sh_issues branch.
