### ISSUE TITLE
Combine the two code import cells

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Sunrise#41]
Combine this code cell with the previous one?

_Originally posted by @Frijol in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ4MzIyMzc5/pull_request_reviews/more_threads_

**Comment by maalvikabhat** [comment]
the link isn't working so I'm not sure what to do here.

**Comment by ericnost** [comment]
Oops! Weird. It's just the first two code cells, the one that "clones" the git repos and the one that import the main libraries.

**Comment by maalvikabhat** [comment]
oh got it! on it.
