### ISSUE TITLE
Error cloning ECHO-Sunrise 'main' branch - in Google colab

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Sunrise#49]
`!git clone -b main --single-branch https://github.com/edgi-govdata-archiving/ECHO-Sunrise.git`

Cloning into 'ECHO-Sunrise'...
warning: Could not find remote branch main to clone.
fatal: Remote branch main not found in upstream origin

**Comment by ericnost** [comment]
Huh. I don't remember deleting the main branch....but it's gone!

The good news is that if you just change this to master it'll work

**Comment by ericnost** [comment]
Ah, Kelsey deleted it. It really is ok though, just switch to 'master', which is where main was merged to. After we do all these fixes, we'll branch the updated master off into main again, and set main as the default, per EDGI's new protocol. If that makes sense!

**Comment by ericnost** [comment]
Fixed by #50
