### ISSUE TITLE
Merge common code into ECHO_modules

### ISSUE THREAD

**Issue by shansen5** [edgi-govdata-archiving/ECHO-Sunrise#57]
Extract code that can be used in multiple notebooks.  Update the DataSet class to accommodate this notebook as well as others.  Consider moving make_data_sets.py back into the common ECHO_modules repository.

**Comment by ericnost** [comment]
Hi @shansen5! I merged the postgresql version of the Sunrise notebook. In the number 3 I get the following error:

```
...
# Get the EPA data from the Stony Brook University database
echo_data = read_echo_data()
...
```

`NameError: name 'read_echo_data' is not defined`

Is `read_echo_data` from ECHO-Modules? Or utilities.py?
