### ISSUE TITLE
Add chart(s) 

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/ECHO-Sunrise#6]
In this first draft, there are no charts visualized - just maps and tables. But, I think we could turn block 7 (rank each geography) into a chart. So, instead of a tabular list of counties ranked by their GHG emissions (or whatever geography and data type is selected), we could have a _barchart_ or other visualization showing this. Would that make sense?

We could use Seaborn to do this: https://github.com/edgi-govdata-archiving/EEW_Planning/issues/153

**Comment by ericnost** [comment]
Hooray, added in #8 / #9 ! 

Now to think about an EJ-oriented chart... #7

**Comment by maalvikabhat** [comment]
It's not allowing me to close this issue, but it is done!
